version: '3.3'
services:
  front-docker:
    image: ghcr.io/artidsun/int222-frontend:latest
    container_name: frontend
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - /home/dohttps/nginx/data/.well-known/pki-validation:/app/.well-known/pki-validation
      - /home/dohttps/nginx:/var/log/nginx/
      - /home/dohttps/nginx/ssl:/ssl/
networks:
    default:
      external:
        name: project2-net