version: '3.3'
services:
  front-docker:
    image: ghcr.io/artidsun/int222-frontend-dev:latest
    container_name: frontend-dev
    ports:
      - "8080:80"
networks:
    default:
      external:
        name: project2-net