version: '3.3'
services:
  front-docker:
    image: ghcr.io/artidsun/int222-frontend:latest
    container_name: frontend
    ports:
      - "8080:8080"
    COPY: /home/project/int222-frontend2/nginx.conf /etc/nginx/nginx.conf
networks:
    default:
      external:
        name: project2-net  